export interface Barangay {
    id: string;
    name: string;
    logo: any; // Using 'any' for local require() images
    punongBarangay: string;
    skChairman: string;
    address: string;
    phone: string;
    email: string;
}

export const DISTRICT_1_BARANGAYS: Barangay[] = [
    // District 1
    {
        id: 'brgy-1-1',
        name: 'BALONG-BATO',
        logo: require('../../assets/images/district/dist1/BALONGBATO.png'),
        punongBarangay: 'Alvin G. Alonzo',
        skChairman: 'Marivic Mabutol',
        address: '41 F. Roman St., Brgy. Balong-Bato, San Juan City',
        phone: '8723-9561',
        email: 'brgybalongbato@gmail.com',
    },
    {
        id: 'brgy-1-2',
        name: 'BATIS',
        logo: require('../../assets/images/district/dist1/BATIS.png'),
        punongBarangay: 'Dino G. Geneston',
        skChairman: 'Shereena Tan',
        address: '420 F Manalo St, Batis, San Juan',
        phone: '7744-0737',
        email: 'batis.sanjuan@gmail.com',
    },
    {
        id: 'brgy-1-3',
        name: 'CORAZON DE JESUS',
        logo: require('../../assets/images/district/dist1/CORAZON.png'),
        punongBarangay: 'Medardo E. Cabubas Jr.',
        skChairman: 'Aisencarl C. Crisologo',
        address: '480 Lt. Artiaga, San Juan City',
        phone: '8811-6227',
        email: 'cdjhealthcenter@gmail.com',
    },
    {
        id: 'brgy-1-4',
        name: 'ERMITAÑO',
        logo: require('../../assets/images/district/dist1/ERMITAÑO.png'),
        punongBarangay: 'Romeo G. Nabong',
        skChairman: 'Chrysanthemum A. Buena',
        address: '187 F. Santos Street, San Juan',
        phone: '7919-4885',
        email: 'sanjuanermitano@gmail.com',
    },
    {
        id: 'brgy-1-5',
        name: 'PASADENA',
        logo: require('../../assets/images/district/dist1/PASADENA.png'),
        punongBarangay: 'Jaime O. Venal',
        skChairman: 'Francine Gil',
        address: 'J25M+9FJ, F.Benitez, San Juan City',
        phone: '7745-3451',
        email: 'publicinfo@sanjuancity.gov.ph',
    },
    {
        id: 'brgy-1-6',
        name: 'PEDRO CRUZ',
        logo: require('../../assets/images/district/dist1/PEDROCRUZ.png'),
        punongBarangay: 'Marylou V. Regino',
        skChairman: 'Uno Miguel',
        address: '1 J. Basa, San Juan City',
        phone: '8288-6467',
        email: 'brgypedrocruz.sanjuancity@gmail.com',
    },
    {
        id: 'brgy-1-7',
        name: 'PROGRESO',
        logo: require('../../assets/images/district/dist1/PROGRESO.png'),
        punongBarangay: 'Flor Marie Joy R. Cabacungan',
        skChairman: 'Laurice Audrey D. Cruz',
        address: 'J22C+V5Q, San Juan City',
        phone: '8727-5635',
        email: 'publicinfo@sanjuancity.gov.ph',
    },
    {
        id: 'brgy-1-8',
        name: 'RIVERA',
        logo: require('../../assets/images/district/dist1/RIVERA.png'),
        punongBarangay: 'Wilfredo F. Reyes',
        skChairman: 'Maria ONeal S. Mendoza-Arquero',
        address: '26 G.B Santos, San Juan City',
        phone: '8942-2543',
        email: 'publicinfo@sanjuancity.gov.ph',
    },
    {
        id: 'brgy-1-9',
        name: 'SALAPAN',
        logo: require('../../assets/images/district/dist1/SALAPAN.png'),
        punongBarangay: 'Charles D. Tejoso',
        skChairman: 'Alliya Loren L. De Guzman',
        address: '38 J. Ruiz Street, San Juan',
        phone: '8251-3116',
        email: 'brgy.salapan@gmail.com',
    },
    {
        id: 'brgy-1-10',
        name: 'SAN PERFECTO',
        logo: require('../../assets/images/district/dist1/SANPERFECTO.png'),
        punongBarangay: 'Arnold Santos',
        skChairman: 'Patricia Salvador',
        address: '51 M. Salvador, San Juan City',
        phone: '8633-3596',
        email: 'publicinfo@sanjuancity.gov.ph',
    },
];

export const DISTRICT_2_BARANGAYS: Barangay[] = [
    // District 2
    {
        id: 'brgy-2-1',
        name: 'ADDITION HILLS',
        logo: require('../../assets/images/district/dist2/ADDITIONHILLS.png'),
        punongBarangay: 'Herbert O. Chua',
        skChairman: 'N/A',
        address: 'E. Rodriguez Street',
        phone: '8352-0211',
        email: 'additionhills@yahoo.com.ph',
    },
    {
        id: 'brgy-2-2',
        name: 'GREENHILLS',
        logo: require('../../assets/images/district/dist2/GREENHILLS.png'),
        punongBarangay: 'Alan T. Yam',
        skChairman: 'Lorenzo Tañada-Yam',
        address: '11 Annapolis St., Greenhills, San Juan City, Metro Manila',
        phone: '8367-9339',
        email: 'publicinfo@sanjuancity.gov.ph',
    },
    {
        id: 'brgy-2-3',
        name: 'ISABELITA',
        logo: require('../../assets/images/district/dist2/ISABELITA.png'),
        punongBarangay: 'Imelda C. Corre',
        skChairman: 'Kyla J. Maristela',
        address: 'Brgy. Isabelita, San Juan City',
        phone: '8722-69482',
        email: 'skcouncil.isabelita@gmail.com',
    },
    {
        id: 'brgy-2-4',
        name: 'KABAYANAN',
        logo: require('../../assets/images/district/dist2/KABAYANAN.png'),
        punongBarangay: 'Christopher S. Punzalan',
        skChairman: 'Aisencarl C. Crisologo',
        address: '8 G. Soriano, Manila, Metro Manila',
        phone: '8461-7073',
        email: 'kabayanan.sanjuan@gmail.com',
    },
    {
        id: 'brgy-2-5',
        name: 'LITTLE BAGUIO',
        logo: require('../../assets/images/district/dist2/LILBAGUIO.png'),
        punongBarangay: 'Ricky Silvano',
        skChairman: 'Cherish Hannah C. Adelan',
        address: 'Unit 309, TNA building, 17 Jose Abad Santos, San Juan City',
        phone: '8661-7493',
        email: 'littlebaguio.sanjuan@gmail.com',
    },
    {
        id: 'brgy-2-6',
        name: 'MAYTUNAS',
        logo: require('../../assets/images/district/dist2/MAYTUNAS.png'),
        punongBarangay: 'Ryan Sequerra',
        skChairman: 'Magel Luciano',
        address: 'V. Cruz Corner M.H Del Pilar Street, San Juan City',
        phone: '8722-7848',
        email: 'publicinfo@sanjuancity.gov.ph',
    },
    {
        id: 'brgy-2-7',
        name: 'ONSE',
        logo: require('../../assets/images/district/dist2/ONSE.png'),
        punongBarangay: 'Roberto Alba',
        skChairman: 'John Michael D. Permato',
        address: '3 J.V. Panganiban, San Juan City',
        phone: '7744-0747',
        email: 'brgyonse@gmail.com',
    },
    {
        id: 'brgy-2-8',
        name: 'SAINT JOSEPH',
        logo: require('../../assets/images/district/dist2/STJOSEPH.png'),
        punongBarangay: 'Regina Hababag',
        skChairman: 'John Rovic Lim',
        address: 'Josephville, San Juan City',
        phone: '09688832234',
        email: 'publicinfo@sanjuancity.gov.ph',
    },
    {
        id: 'brgy-2-9',
        name: 'SANTA LUCIA',
        logo: require('../../assets/images/district/dist2/SANTALUCIA.png'),
        punongBarangay: 'Dennis Pardinez',
        skChairman: 'John Bryan Dela Cruz',
        address: '1 B. S. Angeles, San Juan City',
        phone: '8726-5385',
        email: 'publicinfo@sanjuancity.gov.ph',
    },
    {
        id: 'brgy-2-10',
        name: 'TIBAGAN',
        logo: require('../../assets/images/district/dist2/TIBAGAN.png'),
        punongBarangay: 'N/A',
        skChairman: 'N/A',
        address: '7 R. Pascual St., Tibagan, San Juan City',
        phone: '8723-9837',
        email: 'publicinfo@sanjuancity.gov.ph',
    },
    {
        id: 'brgy-2-11',
        name: 'WEST CRAME',
        logo: require('../../assets/images/district/dist2/WESTCRAME.png'),
        punongBarangay: 'Marcelino Trinidad',
        skChairman: 'Boni Masalihit Manzano',
        address: '1st West Crame, Eisenhower-Crame, San Juan',
        phone: '8635-0169',
        email: 'westcramebrgy@gmail.com',
    },
];

